In [1]:
import pandas as pd
from pathlib import Path

csv_path = Path.cwd().parent / 'FREDcpi.csv'
cpi_data = pd.read_csv(csv_path)
cpi_data.head()

  observation_date  CORESTICKM159SFRBATL
0       1968-01-01              3.651861
1       1968-02-01              3.673819
2       1968-03-01              4.142164
3       1968-04-01              4.155828
4       1968-05-01              4.088245

In [2]:
# observation_date is a date string in YYYY-MM-DD format (no time component).
dates = pd.to_datetime(cpi_data['observation_date'], format='%Y-%m-%d')
cpi_data['Month'] = dates.dt.month
cpi_data['Year'] = dates.dt.year
cpi_data = cpi_data.rename(columns={'CORESTICKM159SFRBATL': 'cpi_pct'})
cpi_data.head()

  observation_date   cpi_pct  Month  Year
0       1968-01-01  3.651861      1  1968
1       1968-02-01  3.673819      2  1968
2       1968-03-01  4.142164      3  1968
3       1968-04-01  4.155828      4  1968
4       1968-05-01  4.088245      5  1968

In [3]:
def get_cpi():
    return cpi_data