In [1]:
import pandas as pd
from pathlib import Path

csv_path = Path.cwd().parent / 'FREDffer.csv'
dff_data = pd.read_csv(csv_path)
dff_data.head()

  observation_date   DFF
0       1954-07-01  1.13
1       1954-07-02  1.25
2       1954-07-03  1.25
3       1954-07-04  1.25
4       1954-07-05  0.88

In [2]:
# observation_date is a date string in YYYY-MM-DD format (no time component).
dates = pd.to_datetime(dff_data['observation_date'], format='%Y-%m-%d')
dff_data['Month'] = dates.dt.month
dff_data['Year'] = dates.dt.year
dff_data = dff_data.rename(columns={'DFF': 'fedfunds_rate'})
dff_data.head()

  observation_date  fedfunds_rate  Month  Year
0       1954-07-01           1.13      7  1954
1       1954-07-02           1.25      7  1954
2       1954-07-03           1.25      7  1954
3       1954-07-04           1.25      7  1954
4       1954-07-05           0.88      7  1954

In [3]:
def get_dff():
    return dff_data