In [4]:
import pandas as pd
from pathlib import Path

csv_path = Path.cwd().parent / 'CIVPART.csv'
civpart_data = pd.read_csv(csv_path)
civpart_data.head()

  observation_date  CIVPART
0       1948-01-01     58.6
1       1948-02-01     58.9
2       1948-03-01     58.5
3       1948-04-01     59.0
4       1948-05-01     58.3

In [5]:
# observation_date is a date string in YYYY-MM-DD format (no time component).
dates = pd.to_datetime(civpart_data['observation_date'], format='%Y-%m-%d')
civpart_data['Month'] = dates.dt.month
civpart_data['Year'] = dates.dt.year

civpart_data.head()

  observation_date  CIVPART  Month  Year
0       1948-01-01     58.6      1  1948
1       1948-02-01     58.9      2  1948
2       1948-03-01     58.5      3  1948
3       1948-04-01     59.0      4  1948
4       1948-05-01     58.3      5  1948

In [6]:
def get_civpart():
    return civpart_data